name: On Push

on: push

jobs:
  deploy-on-push:
    # Name the Job
    name: The code deployed to aws
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1

      - name: yarn install dependencies
        run: yarn --frozen-lockfile

      - name: Serverless
        uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
        with:
          args: deploy
